config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'weather/index'
  # resources :weather
  # devise_for :admin
  # admin_root_path to: "home#index"
  resources :weather
  root to: "weather#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current_weather.rb
class CurrentWeather < ApplicationRecord
  alias_attribute :city_id, :id
  self.primary_key = "id"

  has_many :user_weather_locations
  has_many :users, through: :user_weather_locations, source: :city_id

  def self.new_from_zip(zip)
    weather = $open_weather_api.current(zip: zip)
    self.new(weather)
  end

  def self.create_from_zip(zip)
    self.new_from_zip(zip).save
  end

  def uptodate?
    if Time.now - Time.at((self.dt)) < (3600)
      return true
    else
      return false
    end
  end

  def uptodate
    if !uptodate?
      return self.update($open_weather_api.current(id: self.city_id))
    else
      return self
    end
  end

  def self.uptodate(current_weathers)
    output = []
    current_weathers.each do |current_weather|
      output << current_weather.uptodate
    end
    return output
  end

  def current_temp
    return (('%.f' % (self.main["temp"]*9/5-459.67))+'°F')
  end

  def low_temp
    return (('%.f' % (self.main["temp_min"]*9/5-459.67))+'°F')
  end

  def high_temp
    return (('%.f' % (self.main["temp_max"]*9/5-459.67))+'°F')
  end

  def timestamp
    return self.updated_at.localtime.strftime("%m/%d/%Y %I:%M%p")
  end


  def description
    description = ""
    self.weather.each do |info|
      description << info["description"]
    end
    return description
  end

  def weather_icon
    $open_weather_api.icon_url(self['weather'].first['icon'])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController

  def index
  end

  def create
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/current_weather_helper.rb
module CurrentWeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ethunk's Weather</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/_current_weather_box.html.erb
<!-- <div class='row expand-column-wrapper'>
  <% weathers.each do |weather| %>
    <div class="row column large-3">
      <div> <%= weather.name %> </div>
      <div><img src="<%=weather.weather_icon%>"></div>
      <div class="expand-display"> <%= weather.description %> </div>
      <div> <%= weather.current_temp %> </div>
      <div> High: <%= weather.high_temp %> Low: <%= weather.low_temp %> </div>
    </div>
  <% end %>

</div> -->


<div class="grid-container">
  <div class="grid-x grid-padding-x small-up-2 medium-up-3">
  <% weathers.each do |weather| %>
    <div class="card">
      <div class="cell">
        <div class="card-divider text-center weather-name"> <%= weather.name %> </div>
        <div class="card-section text-center"><img src="<%=weather.weather_icon%>"></div>
        <div class="centered"> <%= weather.description %> </div>
        <div class="centered"> <%= weather.current_temp %> </div>
        <div class="centered"> High: <%= weather.high_temp %> Low: <%= weather.low_temp %> </div>
        <div class="centered end"> <%= weather.timestamp %> </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/weather/_weather_station_form.html.erb
<div class = 'container'>
  <%= form_tag("../weather", method: "post") do %>
    <%= label_tag(:zipcode, "Enter Zipcode:") %>
    <%= text_field_tag(:zipcode) %>
    <%= submit_tag("Add Location") %>
  <% end %>
</div>

app/views/weather/index.html.erb
<div class='box-grid'>
  <p><%= link_to "Add Weather Station", new_weather_path, :id => 'submit_link', :class => 'button' %></p>
</div>

<div class="grid-x grid-padding-x small-up-2 medium-up-3">
    <%= render partial: 'current_weather_box', :locals => { :weathers => @current_weathers } %>
</div>

app/views/weather/new.html.erb
<h1 class='header'>Add Weather Station</h1>
<div class='box-grid'>
  <%= render 'weather_station_form' %>
</div>